name: mazhi_batmi
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+3
  photo_view: ^0.14.0
  image: ^3.0.1
  permission_handler: ^10.0.0
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  google_fonts: ^2.3.2
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  flutter_plugin_android_lifecycle: any
  supabase_flutter: any
  flutter_share: ^2.0.0
  http: ^0.13.6
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  firebase_core: ^3.12.1
  firebase_dynamic_links: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - logo.png
    - assets/login.svg
    - assets/user.png
    - assets/Empty.svg
    - assets/NotFound.svg
    - assets/Empty-folder.svg
    - assets/UnSave.svg
    - assets/Delete_Post.svg
    - assets/_splash.svg
