// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_VHRy00hhae6nOujAjilbsC87ozpTUhc',
    appId: '1:1081272927287:web:389df6644fdad3c8262bb2',
    messagingSenderId: '1081272927287',
    projectId: 'mazhi-batmi',
    authDomain: 'mazhi-batmi.firebaseapp.com',
    databaseURL: 'https://mazhi-batmi-default-rtdb.firebaseio.com',
    storageBucket: 'mazhi-batmi.firebasestorage.app',
    measurementId: 'G-Y7CQ0HWC0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcAWZ3W6gWfT29r2C3q089sJFdXpq5pZo',
    appId: '1:1081272927287:android:c2d9c2db06a746fc262bb2',
    messagingSenderId: '1081272927287',
    projectId: 'mazhi-batmi',
    databaseURL: 'https://mazhi-batmi-default-rtdb.firebaseio.com',
    storageBucket: 'mazhi-batmi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSnGLJMwUoRQCpHhPdtfKJP-HChlQ990s',
    appId: '1:1081272927287:ios:2584a0ba23f08117262bb2',
    messagingSenderId: '1081272927287',
    projectId: 'mazhi-batmi',
    databaseURL: 'https://mazhi-batmi-default-rtdb.firebaseio.com',
    storageBucket: 'mazhi-batmi.firebasestorage.app',
    iosClientId: '1081272927287-79lvnd61gdjqr17igp2kkrb39p0i1gtb.apps.googleusercontent.com',
    iosBundleId: 'com.example.mazhiBatmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSnGLJMwUoRQCpHhPdtfKJP-HChlQ990s',
    appId: '1:1081272927287:ios:2584a0ba23f08117262bb2',
    messagingSenderId: '1081272927287',
    projectId: 'mazhi-batmi',
    databaseURL: 'https://mazhi-batmi-default-rtdb.firebaseio.com',
    storageBucket: 'mazhi-batmi.firebasestorage.app',
    iosClientId: '1081272927287-79lvnd61gdjqr17igp2kkrb39p0i1gtb.apps.googleusercontent.com',
    iosBundleId: 'com.example.mazhiBatmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_VHRy00hhae6nOujAjilbsC87ozpTUhc',
    appId: '1:1081272927287:web:1bcdb6765fb994d4262bb2',
    messagingSenderId: '1081272927287',
    projectId: 'mazhi-batmi',
    authDomain: 'mazhi-batmi.firebaseapp.com',
    databaseURL: 'https://mazhi-batmi-default-rtdb.firebaseio.com',
    storageBucket: 'mazhi-batmi.firebasestorage.app',
    measurementId: 'G-YENZ4VN3FV',
  );

}